lol-honor:
    data:
        dayOneSeen: true
    schemaVersion: 1
lol-parties:
    data:
        hasSeenOpenPartyTooltip: true
    schemaVersion: 1
lol-premade-voice:
    data:
        autoJoin: true
        inputMode: "voiceActivity"
        muteOnConnect: false
        pushToTalkKey: "[<Unbound>]"
        showFirstExperienceInGame: true
        showFirstExperienceInLCU: true
    schemaVersion: 1
lol-tutorial:
    data:
        championSelectRunesTooltipSeenCount: 9
        emotesTutotorialModalDisplayed: true
        perksPresetPagesSeen: true
    schemaVersion: 1
