lol-audio:
    data:
        masterSoundEnabled: false
    schemaVersion: 5
lol-leagues:
    data:
        season-start-takeover:
            season: 8
    schemaVersion: 1
lol-premade-voice:
    data:
        currentCaptureDeviceHandle: "Default System Device"
        inputVolume: 50
        vadSensitivity: 65
    schemaVersion: 1
lol-replays:
    data:
        dontShowEogUsageTip: true
    schemaVersion: 1
lol-skins-viewer:
    data:
        completeSetIdMap: null
        lastSessionId: "eyJraWQiOiJvbmNVIiwiYWxnIjoiUlMyNTYifQ.eyJzdWIiOiIzMjQ4ZGQ3NS04YTZjLTVkOTgtOTUyMi00ZWZiODBkODRkZGQiLCJhdWQiOiJsb2wiLCJpc3MiOiJodHRwczpcL1wvbG9sLnFxLmNvbSIsImxvbCI6W3sidWlkIjo0MDIwMzE4NDUwLCJjdWlkIjo0MDIwMzE4NDUwLCJ1bmFtZSI6IjQwMjAzMTg0NTAiLCJjcGlkIjoiSE4xMiIsInBpZCI6IkhOMTIifV0sInRhZyI6W10sImV4cCI6MTUyMzUwMDkwOSwiaWF0IjoxNTIzNDE0NTA5fQ.FWfrkhqfM0uz1S9TVzRC75Fgiz9nZvZYXt7SoPkRdIM4ZE-dkgWO3LyTr0oIkj-0gD-i66JfmDhuHOJ48SYRBSNVVgbPK6zSdr0SM7VYH3wp8PUSJGof05-rTgfuvYdFujS3lm4Ws2A7CzdXcfJRGd7NjlQ1_7ATKpqgGnNT3_qwcLLIbA-AYeI4asGBO5bG3fxDsj2u8S6JrIHvrNIbUvNGqaZk_z_HpnspD5P6mbKgpZtyAU_EGmYv4xWzAkvxiGlxT5gtpP_MA65KPgTrcj3EyEykGwvD3yH9q_IWnjO3Ya8gi02mt2DzEnhXWY_jh3qQSRPaLf7Ab5YyNu3Img"
        lastVisitTime: 1523414533044
        visitedSkinList: []
    schemaVersion: 1
lol-user-experience:
    data:
        lastKnownMachineSpec: 5
    schemaVersion: 2
video:
    data:
        ZoomScale: 1
    schemaVersion: 1
