install:
    game-settings:
        accountId: 4020318450
        modified: false
        timestamp: 1523418980205
    gameflow-patcher-lock: 1523420193106
    gameflow-process-info:
        pid: 8468
        rawArgs:
        - "8394"
        - "LeagueClient.exe"
        - "/path"
        - "182.140.168.88 5189 yJi3SwO/HKXiMLsTCcdRLQ== 4020318450"
        - "-PlayerID=4020318450"
        - "-GameID=1301923061"
    gameflow-spectate-reconnect-info: null
    globals:
        locale: "zh_CN"
        region: "TENCENT"
    icon_version: 2
    last-valid-login-splash:
        theme: "irelia"
        version: "1.31"
    lcu-settings:
        accountId: 4020318450
        modified: false
        timestamp: 1523414561526
    login-remember-me:
        rememberMe: false
        username: ""
    opt-in-has-migrated-v2: true
    opt-in-migration-attempts-remaining-v3: 2
    perks-settings:
        accountId: 4020318450
        modified: false
        timestamp: 1523414581608
    rso-auth:
        install-identifier: "c1b07b5686fad3429cd3acb5fbdec138"
    splash:
        disableAnimation: true
    telemetry:
        installation_id: "a5/rdA=="
