page-settings:
    data:
        pages: []
        perShardPerkBooks:
            hn12:
                currentPageId: 52
                pages: []
        settings:
            gameplayPatchVersionSeen: "8.7"
            gameplayUpdatedPerksSeen: []
            gridModeEnabled: false
            showLongDescriptions: false
            showPresetPages: true
    schemaVersion: 5
